//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//


package ch.forum_datenaustausch.invoice400;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for headerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sender" type="{http://www.forum-datenaustausch.ch/de}xtendHeaderPartyType"/&gt;
 *         &lt;element name="intermediate" type="{http://www.forum-datenaustausch.ch/de}headerPartyType"/&gt;
 *         &lt;element name="recipient" type="{http://www.forum-datenaustausch.ch/de}xtendHeaderPartyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerType", propOrder = {
    "sender",
    "intermediate",
    "recipient"
})
public class HeaderType {

    @XmlElement(required = true)
    protected XtendHeaderPartyType sender;
    @XmlElement(required = true)
    protected HeaderPartyType intermediate;
    @XmlElement(required = true)
    protected XtendHeaderPartyType recipient;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link XtendHeaderPartyType }
     *     
     */
    public XtendHeaderPartyType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link XtendHeaderPartyType }
     *     
     */
    public void setSender(XtendHeaderPartyType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the intermediate property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderPartyType }
     *     
     */
    public HeaderPartyType getIntermediate() {
        return intermediate;
    }

    /**
     * Sets the value of the intermediate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderPartyType }
     *     
     */
    public void setIntermediate(HeaderPartyType value) {
        this.intermediate = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link XtendHeaderPartyType }
     *     
     */
    public XtendHeaderPartyType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link XtendHeaderPartyType }
     *     
     */
    public void setRecipient(XtendHeaderPartyType value) {
        this.recipient = value;
    }

}
