//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//


package ch.forum_datenaustausch.invoice400;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for invoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="remark" type="{http://www.forum-datenaustausch.ch/de}stringType1_350" minOccurs="0"/&gt;
 *         &lt;element name="creditInfo" type="{http://www.forum-datenaustausch.ch/de}creditInfoType" minOccurs="0"/&gt;
 *         &lt;element name="balance" type="{http://www.forum-datenaustausch.ch/de}balanceType"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="esr5" type="{http://www.forum-datenaustausch.ch/de}esr5Type"/&gt;
 *           &lt;element name="esr9" type="{http://www.forum-datenaustausch.ch/de}esr9Type"/&gt;
 *           &lt;element name="esrRed" type="{http://www.forum-datenaustausch.ch/de}esrRedType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="tiers_garant" type="{http://www.forum-datenaustausch.ch/de}garantType"/&gt;
 *           &lt;element name="tiers_payant" type="{http://www.forum-datenaustausch.ch/de}payantType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="detail" type="{http://www.forum-datenaustausch.ch/de}detailType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="invoice_timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" /&gt;
 *       &lt;attribute name="invoice_id" use="required" type="{http://www.forum-datenaustausch.ch/de}stringType1_35" /&gt;
 *       &lt;attribute name="invoice_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="resend" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="case_id" type="{http://www.forum-datenaustausch.ch/de}stringType1_35" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceType", propOrder = {
    "remark",
    "creditInfo",
    "balance",
    "esr5",
    "esr9",
    "esrRed",
    "tiersGarant",
    "tiersPayant",
    "detail"
})
public class InvoiceType {

    protected String remark;
    protected CreditInfoType creditInfo;
    @XmlElement(required = true)
    protected BalanceType balance;
    protected Esr5Type esr5;
    protected Esr9Type esr9;
    protected EsrRedType esrRed;
    @XmlElement(name = "tiers_garant")
    protected GarantType tiersGarant;
    @XmlElement(name = "tiers_payant")
    protected PayantType tiersPayant;
    @XmlElement(required = true)
    protected DetailType detail;
    @XmlAttribute(name = "invoice_timestamp", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger invoiceTimestamp;
    @XmlAttribute(name = "invoice_id", required = true)
    protected String invoiceId;
    @XmlAttribute(name = "invoice_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar invoiceDate;
    @XmlAttribute(name = "resend")
    protected Boolean resend;
    @XmlAttribute(name = "case_id")
    protected String caseId;

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the creditInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreditInfoType }
     *     
     */
    public CreditInfoType getCreditInfo() {
        return creditInfo;
    }

    /**
     * Sets the value of the creditInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditInfoType }
     *     
     */
    public void setCreditInfo(CreditInfoType value) {
        this.creditInfo = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceType }
     *     
     */
    public BalanceType getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceType }
     *     
     */
    public void setBalance(BalanceType value) {
        this.balance = value;
    }

    /**
     * Gets the value of the esr5 property.
     * 
     * @return
     *     possible object is
     *     {@link Esr5Type }
     *     
     */
    public Esr5Type getEsr5() {
        return esr5;
    }

    /**
     * Sets the value of the esr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esr5Type }
     *     
     */
    public void setEsr5(Esr5Type value) {
        this.esr5 = value;
    }

    /**
     * Gets the value of the esr9 property.
     * 
     * @return
     *     possible object is
     *     {@link Esr9Type }
     *     
     */
    public Esr9Type getEsr9() {
        return esr9;
    }

    /**
     * Sets the value of the esr9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esr9Type }
     *     
     */
    public void setEsr9(Esr9Type value) {
        this.esr9 = value;
    }

    /**
     * Gets the value of the esrRed property.
     * 
     * @return
     *     possible object is
     *     {@link EsrRedType }
     *     
     */
    public EsrRedType getEsrRed() {
        return esrRed;
    }

    /**
     * Sets the value of the esrRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link EsrRedType }
     *     
     */
    public void setEsrRed(EsrRedType value) {
        this.esrRed = value;
    }

    /**
     * Gets the value of the tiersGarant property.
     * 
     * @return
     *     possible object is
     *     {@link GarantType }
     *     
     */
    public GarantType getTiersGarant() {
        return tiersGarant;
    }

    /**
     * Sets the value of the tiersGarant property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarantType }
     *     
     */
    public void setTiersGarant(GarantType value) {
        this.tiersGarant = value;
    }

    /**
     * Gets the value of the tiersPayant property.
     * 
     * @return
     *     possible object is
     *     {@link PayantType }
     *     
     */
    public PayantType getTiersPayant() {
        return tiersPayant;
    }

    /**
     * Sets the value of the tiersPayant property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayantType }
     *     
     */
    public void setTiersPayant(PayantType value) {
        this.tiersPayant = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link DetailType }
     *     
     */
    public DetailType getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailType }
     *     
     */
    public void setDetail(DetailType value) {
        this.detail = value;
    }

    /**
     * Gets the value of the invoiceTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvoiceTimestamp() {
        return invoiceTimestamp;
    }

    /**
     * Sets the value of the invoiceTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvoiceTimestamp(BigInteger value) {
        this.invoiceTimestamp = value;
    }

    /**
     * Gets the value of the invoiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * Sets the value of the invoiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceId(String value) {
        this.invoiceId = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the resend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResend() {
        if (resend == null) {
            return false;
        } else {
            return resend;
        }
    }

    /**
     * Sets the value of the resend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResend(Boolean value) {
        this.resend = value;
    }

    /**
     * Gets the value of the caseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

}
