//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//


package ch.forum_datenaustausch.invoice400;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.forum_datenaustausch.invoice400 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://www.forum-datenaustausch.ch/de", "request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.forum_datenaustausch.invoice400
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ZipType }
     * 
     */
    public ZipType createZipType() {
        return new ZipType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link TelecomAddressType }
     * 
     */
    public TelecomAddressType createTelecomAddressType() {
        return new TelecomAddressType();
    }

    /**
     * Create an instance of {@link OnlineAddressType }
     * 
     */
    public OnlineAddressType createOnlineAddressType() {
        return new OnlineAddressType();
    }

    /**
     * Create an instance of {@link EmployerAddressType }
     * 
     */
    public EmployerAddressType createEmployerAddressType() {
        return new EmployerAddressType();
    }

    /**
     * Create an instance of {@link BillerAddressType }
     * 
     */
    public BillerAddressType createBillerAddressType() {
        return new BillerAddressType();
    }

    /**
     * Create an instance of {@link ProviderAddressType }
     * 
     */
    public ProviderAddressType createProviderAddressType() {
        return new ProviderAddressType();
    }

    /**
     * Create an instance of {@link InsuranceAddressType }
     * 
     */
    public InsuranceAddressType createInsuranceAddressType() {
        return new InsuranceAddressType();
    }

    /**
     * Create an instance of {@link PatientAddressType }
     * 
     */
    public PatientAddressType createPatientAddressType() {
        return new PatientAddressType();
    }

    /**
     * Create an instance of {@link GuarantorAddressType }
     * 
     */
    public GuarantorAddressType createGuarantorAddressType() {
        return new GuarantorAddressType();
    }

    /**
     * Create an instance of {@link ReferrerAddressType }
     * 
     */
    public ReferrerAddressType createReferrerAddressType() {
        return new ReferrerAddressType();
    }

    /**
     * Create an instance of {@link BankAddressType }
     * 
     */
    public BankAddressType createBankAddressType() {
        return new BankAddressType();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link RecordTarmedType }
     * 
     */
    public RecordTarmedType createRecordTarmedType() {
        return new RecordTarmedType();
    }

    /**
     * Create an instance of {@link RecordCantonalType }
     * 
     */
    public RecordCantonalType createRecordCantonalType() {
        return new RecordCantonalType();
    }

    /**
     * Create an instance of {@link RecordUnclassifiedType }
     * 
     */
    public RecordUnclassifiedType createRecordUnclassifiedType() {
        return new RecordUnclassifiedType();
    }

    /**
     * Create an instance of {@link RecordDrugType }
     * 
     */
    public RecordDrugType createRecordDrugType() {
        return new RecordDrugType();
    }

    /**
     * Create an instance of {@link RecordLabType }
     * 
     */
    public RecordLabType createRecordLabType() {
        return new RecordLabType();
    }

    /**
     * Create an instance of {@link RecordMigelType }
     * 
     */
    public RecordMigelType createRecordMigelType() {
        return new RecordMigelType();
    }

    /**
     * Create an instance of {@link RecordPhysioType }
     * 
     */
    public RecordPhysioType createRecordPhysioType() {
        return new RecordPhysioType();
    }

    /**
     * Create an instance of {@link RecordDentalType }
     * 
     */
    public RecordDentalType createRecordDentalType() {
        return new RecordDentalType();
    }

    /**
     * Create an instance of {@link KvgLawType }
     * 
     */
    public KvgLawType createKvgLawType() {
        return new KvgLawType();
    }

    /**
     * Create an instance of {@link VvgLawType }
     * 
     */
    public VvgLawType createVvgLawType() {
        return new VvgLawType();
    }

    /**
     * Create an instance of {@link UvgLawType }
     * 
     */
    public UvgLawType createUvgLawType() {
        return new UvgLawType();
    }

    /**
     * Create an instance of {@link IvgLawType }
     * 
     */
    public IvgLawType createIvgLawType() {
        return new IvgLawType();
    }

    /**
     * Create an instance of {@link MvgLawType }
     * 
     */
    public MvgLawType createMvgLawType() {
        return new MvgLawType();
    }

    /**
     * Create an instance of {@link OrgLawType }
     * 
     */
    public OrgLawType createOrgLawType() {
        return new OrgLawType();
    }

    /**
     * Create an instance of {@link DiagnosisType }
     * 
     */
    public DiagnosisType createDiagnosisType() {
        return new DiagnosisType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link GarantType }
     * 
     */
    public GarantType createGarantType() {
        return new GarantType();
    }

    /**
     * Create an instance of {@link PayantType }
     * 
     */
    public PayantType createPayantType() {
        return new PayantType();
    }

    /**
     * Create an instance of {@link Esr5Type }
     * 
     */
    public Esr5Type createEsr5Type() {
        return new Esr5Type();
    }

    /**
     * Create an instance of {@link Esr9Type }
     * 
     */
    public Esr9Type createEsr9Type() {
        return new Esr9Type();
    }

    /**
     * Create an instance of {@link EsrRedType }
     * 
     */
    public EsrRedType createEsrRedType() {
        return new EsrRedType();
    }

    /**
     * Create an instance of {@link VatRateType }
     * 
     */
    public VatRateType createVatRateType() {
        return new VatRateType();
    }

    /**
     * Create an instance of {@link VatType }
     * 
     */
    public VatType createVatType() {
        return new VatType();
    }

    /**
     * Create an instance of {@link BalanceType }
     * 
     */
    public BalanceType createBalanceType() {
        return new BalanceType();
    }

    /**
     * Create an instance of {@link CreditInfoType }
     * 
     */
    public CreditInfoType createCreditInfoType() {
        return new CreditInfoType();
    }

    /**
     * Create an instance of {@link HeaderPartyType }
     * 
     */
    public HeaderPartyType createHeaderPartyType() {
        return new HeaderPartyType();
    }

    /**
     * Create an instance of {@link XtendHeaderPartyType }
     * 
     */
    public XtendHeaderPartyType createXtendHeaderPartyType() {
        return new XtendHeaderPartyType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link GeneratorType }
     * 
     */
    public GeneratorType createGeneratorType() {
        return new GeneratorType();
    }

    /**
     * Create an instance of {@link DataValidatorType }
     * 
     */
    public DataValidatorType createDataValidatorType() {
        return new DataValidatorType();
    }

    /**
     * Create an instance of {@link PrologType }
     * 
     */
    public PrologType createPrologType() {
        return new PrologType();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.forum-datenaustausch.ch/de", name = "request")
    public JAXBElement<RequestType> createRequest(RequestType value) {
        return new JAXBElement<RequestType>(_Request_QNAME, RequestType.class, null, value);
    }

}
