//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.forum-datenaustausch.ch/de", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.forum_datenaustausch.invoice400;
