//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//


package ch.forum_datenaustausch.invoice400;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for requestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://www.forum-datenaustausch.ch/de}headerType"/&gt;
 *         &lt;element name="prolog" type="{http://www.forum-datenaustausch.ch/de}prologType"/&gt;
 *         &lt;element name="invoice" type="{http://www.forum-datenaustausch.ch/de}invoiceType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="assignment_title" type="{http://www.forum-datenaustausch.ch/de}stringType1_35" /&gt;
 *       &lt;attribute name="assignment_role" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="labtechnician"/&gt;
 *             &lt;enumeration value="orthopaedictechnician"/&gt;
 *             &lt;enumeration value="dentist"/&gt;
 *             &lt;enumeration value="dentaltechnician"/&gt;
 *             &lt;enumeration value="dentalhygienist"/&gt;
 *             &lt;enumeration value="physiotherapist"/&gt;
 *             &lt;enumeration value="ergotherapist"/&gt;
 *             &lt;enumeration value="logotherapist"/&gt;
 *             &lt;enumeration value="chiropraktor"/&gt;
 *             &lt;enumeration value="diet"/&gt;
 *             &lt;enumeration value="diabetics"/&gt;
 *             &lt;enumeration value="massage"/&gt;
 *             &lt;enumeration value="midwife"/&gt;
 *             &lt;enumeration value="wholesaler"/&gt;
 *             &lt;enumeration value="shoemaker"/&gt;
 *             &lt;enumeration value="nurse"/&gt;
 *             &lt;enumeration value="ambulance"/&gt;
 *             &lt;enumeration value="druggist"/&gt;
 *             &lt;enumeration value="carrier"/&gt;
 *             &lt;enumeration value="other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="assignment_place" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="practice"/&gt;
 *             &lt;enumeration value="hospital"/&gt;
 *             &lt;enumeration value="lab"/&gt;
 *             &lt;enumeration value="association"/&gt;
 *             &lt;enumeration value="company"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="role" default="production"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="production"/&gt;
 *             &lt;enumeration value="test"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {
    "header",
    "prolog",
    "invoice"
})
public class RequestType {

    @XmlElement(required = true)
    protected HeaderType header;
    @XmlElement(required = true)
    protected PrologType prolog;
    @XmlElement(required = true)
    protected InvoiceType invoice;
    @XmlAttribute(name = "assignment_title")
    protected String assignmentTitle;
    @XmlAttribute(name = "assignment_role", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String assignmentRole;
    @XmlAttribute(name = "assignment_place", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String assignmentPlace;
    @XmlAttribute(name = "role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String role;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the prolog property.
     * 
     * @return
     *     possible object is
     *     {@link PrologType }
     *     
     */
    public PrologType getProlog() {
        return prolog;
    }

    /**
     * Sets the value of the prolog property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrologType }
     *     
     */
    public void setProlog(PrologType value) {
        this.prolog = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceType }
     *     
     */
    public InvoiceType getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceType }
     *     
     */
    public void setInvoice(InvoiceType value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the assignmentTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentTitle() {
        return assignmentTitle;
    }

    /**
     * Sets the value of the assignmentTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentTitle(String value) {
        this.assignmentTitle = value;
    }

    /**
     * Gets the value of the assignmentRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentRole() {
        return assignmentRole;
    }

    /**
     * Sets the value of the assignmentRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentRole(String value) {
        this.assignmentRole = value;
    }

    /**
     * Gets the value of the assignmentPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentPlace() {
        return assignmentPlace;
    }

    /**
     * Sets the value of the assignmentPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentPlace(String value) {
        this.assignmentPlace = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        if (role == null) {
            return "production";
        } else {
            return role;
        }
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
