//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:25:14 AM EST 
//


package ch.forum_datenaustausch.invoice400;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for servicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="servicesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="record_tarmed" type="{http://www.forum-datenaustausch.ch/de}recordTarmedType"/&gt;
 *         &lt;element name="record_cantonal" type="{http://www.forum-datenaustausch.ch/de}recordCantonalType"/&gt;
 *         &lt;element name="record_unclassified" type="{http://www.forum-datenaustausch.ch/de}recordUnclassifiedType"/&gt;
 *         &lt;element name="record_lab" type="{http://www.forum-datenaustausch.ch/de}recordLabType"/&gt;
 *         &lt;element name="record_migel" type="{http://www.forum-datenaustausch.ch/de}recordMigelType"/&gt;
 *         &lt;element name="record_physio" type="{http://www.forum-datenaustausch.ch/de}recordPhysioType"/&gt;
 *         &lt;element name="record_drug" type="{http://www.forum-datenaustausch.ch/de}recordDrugType"/&gt;
 *         &lt;element name="record_dental" type="{http://www.forum-datenaustausch.ch/de}recordDentalType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servicesType", propOrder = {
    "recordTarmedOrRecordCantonalOrRecordUnclassified"
})
public class ServicesType {

    @XmlElements({
        @XmlElement(name = "record_tarmed", type = RecordTarmedType.class),
        @XmlElement(name = "record_cantonal", type = RecordCantonalType.class),
        @XmlElement(name = "record_unclassified", type = RecordUnclassifiedType.class),
        @XmlElement(name = "record_lab", type = RecordLabType.class),
        @XmlElement(name = "record_migel", type = RecordMigelType.class),
        @XmlElement(name = "record_physio", type = RecordPhysioType.class),
        @XmlElement(name = "record_drug", type = RecordDrugType.class),
        @XmlElement(name = "record_dental", type = RecordDentalType.class)
    })
    protected List<Object> recordTarmedOrRecordCantonalOrRecordUnclassified;

    /**
     * Gets the value of the recordTarmedOrRecordCantonalOrRecordUnclassified property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordTarmedOrRecordCantonalOrRecordUnclassified property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordTarmedOrRecordCantonalOrRecordUnclassified().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecordTarmedType }
     * {@link RecordCantonalType }
     * {@link RecordUnclassifiedType }
     * {@link RecordLabType }
     * {@link RecordMigelType }
     * {@link RecordPhysioType }
     * {@link RecordDrugType }
     * {@link RecordDentalType }
     * 
     * 
     */
    public List<Object> getRecordTarmedOrRecordCantonalOrRecordUnclassified() {
        if (recordTarmedOrRecordCantonalOrRecordUnclassified == null) {
            recordTarmedOrRecordCantonalOrRecordUnclassified = new ArrayList<Object>();
        }
        return this.recordTarmedOrRecordCantonalOrRecordUnclassified;
    }

}
